/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.Utils;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.net.Socket;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author Joao
 */
public class Chat extends javax.swing.JFrame {

    /**
     * Creates new form Chat
     */
    private String dadosConexao;
    private ArrayList<String> mensagens;
    private Home home;
    private Socket conn;
    private String titulo;

    public Chat(Home home, Socket conn, String dadosConexao, String titulo) {
        super("Chat " + titulo);
        this.dadosConexao = dadosConexao;
        this.conn = conn;
        this.home = home;
        initComponents();
        this.setLocationRelativeTo(null);
        mensagens = new ArrayList<String>();
        this.titulo = titulo;
        jlTitulo.setText(dadosConexao.split(":")[0]);
        configComponentes();
        this.setVisible(true);
    }

    private void configComponentes() {
        listaMensagens.setContentType("text/html");
        acoes();

        //jlTitulo = new JLabel(dadosConexao.split(";;;")[0]);
    }
    
    public void acoes(){
        btnEnviar.addActionListener(event -> enviarMensagem());
        tfMensagem.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                
            }

            @Override
            public void keyPressed(KeyEvent e) {
                if(e.getKeyChar() == KeyEvent.VK_ENTER) {
                    enviarMensagem();
                }
            }

            @Override
            public void keyReleased(KeyEvent e) {
                
            }
        });
        this.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
                
            }

            @Override
            public void windowClosing(WindowEvent e) {
                Utils.enviarMensagem(conn, "FECHAR_CHAT");
                home.getChatsAbertos().remove(dadosConexao);
                home.getConectadosListeners().remove(dadosConexao);
                home.getConectadosListeners().get(dadosConexao).setIsChatOpen(false);
                home.getConectadosListeners().get(dadosConexao).setIsRunning(false);
                
            }

            @Override
            public void windowClosed(WindowEvent e) {
                
            }

            @Override
            public void windowIconified(WindowEvent e) {
                
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
                
            }

            @Override
            public void windowActivated(WindowEvent e) {
                
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
                
            }
        });
    }

    public void incrementarMensagem(String mensagem) {
        mensagens.add(mensagem);
        String msg = "";
        for (String str : mensagens) {
            msg += str;
        }
        listaMensagens.setText(msg);
    }

    private void enviarMensagem() {
        if(tfMensagem.getText().length() > 0)
        {
            DateFormat df = new SimpleDateFormat("hh:mm:ss");
            Utils.enviarMensagem(conn, "MENSAGEM;" + "<b>[" + df.format(new Date()) + "] "+this.titulo+": </b><i>" + tfMensagem.getText() + "</i><br>");
            incrementarMensagem("<b>[" + df.format(new Date()) + "] Eu: </b><i>" + tfMensagem.getText() + "</i><br>");
            tfMensagem.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMensagens = new javax.swing.JEditorPane();
        tfMensagem = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jlTitulo.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(204, 0, 0));
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("Nome Usuário");

        listaMensagens.setEditable(false);
        listaMensagens.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        listaMensagens.setForeground(new java.awt.Color(153, 0, 0));
        jScrollPane1.setViewportView(listaMensagens);

        tfMensagem.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        tfMensagem.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfMensagem.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnEnviar.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(153, 0, 0));
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JEditorPane listaMensagens;
    private javax.swing.JTextField tfMensagem;
    // End of variables declaration//GEN-END:variables
}
